on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: npm run build
      - run: npm run test
